name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: repo

    steps:
      - uses: actions/checkout@v6
        with:
          path: repo
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x
      - name: Build ConsoleReader
        run: dotnet build ./src/ConsoleReader/ConsoleReader.csproj --configuration Release -p:RestoreForce=true -p:ImportProjectExtensionProps=false -p:ImportProjectExtensionTargets=false
      - name: Build ReplayWatcher
        run: dotnet build ./src/ReplayWatcher/ReplayWatcher.csproj --configuration Release -p:RestoreForce=true -p:ImportProjectExtensionProps=false -p:ImportProjectExtensionTargets=false
